### ISSUE TITLE
[Feature Request] Paged Reading Mode

### ISSUE THREAD

**Issue by zFerry98** [hkalexling/Mango#106] opened 2020-09-21 17:13 UTC
**Is your feature request related to a problem? Please describe.**
unfortunately the scroll view does not allow some images of the scans to be clearly visible during reading.

**Describe the solution you'd like**
The possibility to change the visualization style of the pages in the reader.
Display style like Komga or MangaDex.

**Describe a small use-case for this feature request**
Chapter scans with close-ups or those that have vertical lines and then pick up the box art on the left / right of the foreground.
Use on mobile from chrome with 5 6 "screens.

**Additional context**
If not as an internal solution to the reader I would be satisfied with a script for tampermonkey as a temporary solution.
Script es to transform the LANRaragi page reader into a scroll view:
![image](https://user-images.githubusercontent.com/17975351/93799380-62dcd400-fc3f-11ea-88fd-3b1490e9c0da.png)

I don't know why but updating to 0.12.2 it keeps giving me 404 if you do next read. The strange thing is that the cli says 0.12.0 despite being 3 times I download and re-update to 0.12.2.

**Comment by hkalexling** [comment] 2020-09-22 04:25
> I don't know why but updating to 0.12.2 it keeps giving me 404 if you do next read. The strange thing is that the cli says 0.12.0 despite being 3 times I download and re-update to 0.12.2.

Hi, the bug has been fixed in v0.12.2. If the CLI says 0.12.0 it means you are not updating Mango correctly and you are still using the outdated version. How did you install Mango? And what did you do to update it to v0.12.2?

**Comment by zFerry98** [comment] 2020-09-22 10:02
I simply download from the release page under 0.12.2 the "Mango" without extension and then copy to the "software" folder in `/home/uadmin/software` in the WSL. I do `sudo chmod + x ./mango122` (because every version I rename it with the number, so you can't go wrong. Ex: Mango 0.11.0> Mango11; Mango 0.10.0> Mango10; Mango 0.12.2> Mango122) and then I start with `./mango122` but when it starts it remains 0.12.0 in the cli, I also tried leaving only the last mango (0.12.2) in the folder but it keeps telling me 0.12.0 in the cli. Anyway now I upgrade to 0.12.3 and see if it was a problem with that specific version.

**Comment by hkalexling** [comment] 2020-09-22 10:35
Great! Now that the issue is out of the way we can focus on your feature request.

Can you elaborate a bit on "Fit image to screen"? Do you want the pages to fit the height or width? 

> Use on mobile from chrome with 5 6 "screens.

If you are using a mobile device I think you can just pinch to zoom in?

**Comment by zFerry98** [comment] 2020-09-22 12:10
When I'm away from home, I use the Nintendo Switch (android 8 on chrome, vertically) and despite the nice big screen, many pages have to scroll to read them first at the bottom and then again at the top (to read the whole table).
The problem is that the mango reader does not allow single pages to be full screen (fit screen) and therefore you have to scroll through things to read the whole page. I don't know if I have made myself clear. Being able to have the reader that each page is full screen (fit screen). Komga differentiates the "fit screen" with "fit height".

### MANGO:
![image](https://user-images.githubusercontent.com/17975351/93875915-32944480-fcd6-11ea-862e-dfa6fc17b416.png)
Example, here says a sentence at the end of the table.

----------------------------------------------------------------------------------------------------------------------------------------------
### KOMGA:
![image](https://user-images.githubusercontent.com/17975351/93876065-74bd8600-fcd6-11ea-9d4d-05f428f99c14.png)
Here, on the other hand, you can immediately read the sentence and then see the image in its entirety (which you cannot do if you do not zoom in / zoom out manually)

Ex:
<details>
  <summary>Spoiler warning My Hero Academia</summary>
  
![image](https://user-images.githubusercontent.com/17975351/93877193-5eb0c500-fcd8-11ea-87ed-d0507b5a84d7.png)
![image](https://user-images.githubusercontent.com/17975351/93877232-6e300e00-fcd8-11ea-9ec2-2069104d6a4c.png)

### Full: 
![image](https://user-images.githubusercontent.com/17975351/93877278-8142de00-fcd8-11ea-9df7-7503b1d31af5.png)

  
</details>

As you can see (even if not in English) reading this table with a scrolling visualization ruins the "flow" forcing first to read each writing, then to look at the whole image. If for each board I have to do the "pinch-in / out" on touchscreens and "ctrl + wheel" on PCs it becomes uncomfortable. Also because then you have to go back to the original dimensions.

<details>
 <summary>Komga Reader Exs:</summary>

![image](https://user-images.githubusercontent.com/17975351/93878686-c49e4c00-fcda-11ea-9a47-281e29bb5d5e.png)
![image](https://user-images.githubusercontent.com/17975351/93878715-d122a480-fcda-11ea-961d-8ed68aeef41b.png)
![image](https://user-images.githubusercontent.com/17975351/93878759-e0a1ed80-fcda-11ea-9ea1-3d6a285533ca.png)
![image](https://user-images.githubusercontent.com/17975351/93878789-ec8daf80-fcda-11ea-9205-82a6415ad45d.png)

### Original view: 
![image](https://user-images.githubusercontent.com/17975351/93878841-04653380-fcdb-11ea-8e2d-5a79d2302ecd.png)
### Fit Screen:
![image](https://user-images.githubusercontent.com/17975351/93878936-2bbc0080-fcdb-11ea-9691-4230d3348d0a.png)
### Original view Page1:
![image](https://user-images.githubusercontent.com/17975351/93879690-75f1b180-fcdc-11ea-9a39-6857d40876bc.png)
### Fit Screen Page 1:
![image](https://user-images.githubusercontent.com/17975351/93879733-8dc93580-fcdc-11ea-85ba-f149e4fe074d.png)
At the bottom the black stripe in the original is no longer in the fit screen.

</details>

On practically any reader (mangaDex, Tachiyomi, Komga and even OPDS ones) it is possible to choose the types of page display.
I said in the first comment.
If introducing these changes is a long-term design thing, if it was possible to have a few lines script (that of tampermonkey) as a temporary solution. Unfortunately I don't know how to program and I don't know anyone to do it. From what I see in the script, it seems to work reading the classes.
Obviously, Thanks in advance.

**Comment by hkalexling** [comment] 2020-09-22 12:25
Ah I see. Thanks for the clarification. I looks like the "fit screen" option in Komga is to fit either the width or height, depending on which is smaller. I agree it could be a useful feature, and I will take a look and see how we can do it.

**Comment by hkalexling** [comment] 2020-10-18 12:44
The paged reader mode has been added in [v0.14.0](https://github.com/hkalexling/Mango/releases/tag/v0.14.0). Thanks for the feature request!

**Closed by hkalexling** 2020-10-18 12:44 UTC
Labels: enhancement
