### ISSUE TITLE
[Bug Report] Outdated Manga-Dex API

### ISSUE THREAD

**Issue by BlyatOrange** [hkalexling/Mango#210] opened 2021-08-04 00:29 UTC
**Describe the bug**

The manga-dex API being used seems to be outdated. Entering a mangadex url into the prompt throws this
> Please make sure you are using a valid manga ID or manga URL from Mangadex. If you are trying to search MangaDex with a search term, please log in to MangaDex first by going to "Admin -> Connect to MangaDex".

and inserting an ID taken from the url (for example: 2f4e5f5b-d930-4266-8c8a-c4cf9a81e51f) throws this

> Failed to get manga info. Error: Failed to get https://api.mangadex.org/v2/manga/x. [410]

**Environment (please complete the following information):**
 - OS: Arch Linux (up-to-date)
 - Browser: Firefox
 - Mango Version: v0.21.0 (pre-compiled bin)

**Additional context**
Add any other context about the problem here. Add screenshots if applicable.

Following the given manga-dex API link manually takes you to a page saying

> You tried to use an endpoint from the MangaDex v3 API
These do not exist anymore!
Check out our new v5 API docs and migrate

Beyond this, the number at the end of the URL given from the error ( api.mangadex.org/v2/manga/**_2_** ) is the same as the first number from the ID given. Unless "ID" means something other than what I'm thinking, this could be a parsing error as well.

**Comment by Nerothos** [comment] 2021-08-04 10:05
Duplicate of https://github.com/hkalexling/Mango/issues/170 , it's being worked on in a way to remove mangadex content from mango to put it in a plugins

**Closed** 2021-08-04 13:14 UTC
Labels: bug

**Comment by hkalexling** [comment] 2021-08-05 08:45
@Nerothos thanks for answering! Yes please subscribe to #170 to get updates on this. I am not able to put in as much time in the development as before due to other duties so it will take a while.
