### ISSUE TITLE
some comic can't load and log report 'Invalid Int32'

### ISSUE THREAD

**Issue by WROIATE** [hkalexling/Mango#22] opened 2020-03-26 08:07 UTC
**Describe the bug**
I can't open some manga on the website even it has been scaned. This manga has title but without cover

**To Reproduce**
1. Go to mango website and tap the manga without cover
2. can't load anything
3. See error log

**Expected behavior**
load normally

**Environment (please complete the following information):**
 - OS: unraid
 - Browser chrome and via
 - Mango Version v0.2.1

**Additional context**
log is here:
`[91m[ERROR] [0m2020/03/26 07:59:07 | Invalid Int32: 14410155591588`

**Comment by hkalexling** [comment] 2020-03-26 15:05
Hi, thanks for the bug report!

Unfortunately I cannot reproduce this. It would be very helpful if you could send me the file(s) causing the problem. You can reach me by emailing email@hkalexling.com

**Comment by WROIATE** [comment] 2020-03-26 16:48
> Hi, thanks for the bug report!
> 
> Unfortunately I cannot reproduce this. It would be very helpful if you could send me the file(s) causing the problem. You can reach me by emailing [email@hkalexling.com](mailto:email@hkalexling.com)

According to my test, I found it's the picture name's problem. There is a picture named '14410155591588.jpg' in the zip file, and mango can't load this picture. When I renamed the picture it works well.  

Perhaps in the code of library.cr have the type error problem (I'm sorry about that I can't read crystal code and give the exact suggetion)

**Comment by hkalexling** [comment] 2020-03-27 05:15
This is fixed in [v0.2.3](https://github.com/hkalexling/Mango/releases/tag/v0.2.3). Thanks for the bug report!

**Closed by hkalexling** 2020-03-27 05:15 UTC
Labels: bug
