### ISSUE TITLE
[Feature Request] Favicon

### ISSUE THREAD

**Issue by flying-sausages** [hkalexling/Mango#55] opened 2020-06-03 12:25 UTC
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/23618693/83636278-96ff8c80-a59d-11ea-8b11-435382988adf.png)

**Describe the solution you'd like**
A little icon to make it easier to find those mango tabs

**Additional context**

**Comment by hkalexling** [comment] 2020-06-03 12:34
Hmm, we do [have it](https://github.com/hkalexling/Mango/blob/master/public/favicon.ico), and it's showing up fine on my machine

Firefox:
<img width="383" alt="Screenshot 2020-06-03 at 8 30 30 PM" src="https://user-images.githubusercontent.com/7845831/83636791-1f4f5300-a5d9-11ea-876a-c68c70441d25.png">

Chrome:
<img width="357" alt="Screenshot 2020-06-03 at 8 30 39 PM" src="https://user-images.githubusercontent.com/7845831/83636802-26766100-a5d9-11ea-8a7a-4bc3016f83a6.png">

Can you access `domain.tld:9000/favicon.ico`?

**Comment by flying-sausages** [comment] 2020-06-03 12:57
Ah interesting, I assume it has something to do with the `baseURL`.
`https://10.146.239.216/mango/favicon.ico` shows the right image.

While we're at it, might be nice to make the mango a bit bigger in the image. it would be nice to just give the mango itself inside of a png with alpha for transparency. If you give me a pointer to where I can find the images I can cook something up and make a PR :)

**Comment by jaredlt** [comment] 2020-06-03 13:05
@flying-sausages the favicon is here https://github.com/hkalexling/Mango/blob/master/public/favicon.ico

I don't know if there are any browser compatibility issues with transparent png favicons but I guess we should target the same support as [UI Kit](https://getuikit.com/docs/introduction#browser-support) (the CSS library used by Mango). @hkalexling ?

**Comment by flying-sausages** [comment] 2020-06-03 13:08
FYI I am on FF 68 ESR

**Comment by hkalexling** [comment] 2020-06-03 13:13
@flying-sausages You are right! By default the browser fetches the icon from `/favicon.ico` and we didn't set the path explicitly in HTML when using base URL. I will fix this in the next version.

@jaredlt Good point 👍  I will investigate the compatibility issues when I have the time.

**Comment by hkalexling** [comment] 2020-06-04 05:08
@jaredlt PNG favicon is [supported](https://caniuse.com/#feat=link-icon-png) in all modern browsers.

@flying-sausages Apart from the favicon link given above, you can find other image assets here https://github.com/hkalexling/Mango/tree/master/public/img

**Comment by hkalexling** [comment] 2020-06-04 15:33
The issue is fixed in [v0.5.2](https://github.com/hkalexling/Mango/releases/tag/v0.5.2). Thanks for the heads up!

**Closed by hkalexling** 2020-06-04 15:33 UTC
Labels: enhancement
