### ISSUE TITLE
[Question] Mangadex inbuilt downloader not showing?

### ISSUE THREAD

**Issue by benchristopher** [hkalexling/Mango#254] opened 2021-12-02 13:24 UTC
Hi, 

Please assit me in locating the inbuilt MangaDex downloader? Cannot seem to find it haha. 

Cheers,

**Comment by hkalexling** [comment] 2021-12-02 13:41
Duplicate of #239. You can subscribe to #170 to get updated.

**Closed by hkalexling** 2021-12-02 13:41 UTC
Labels: general question
