### ISSUE TITLE
[Bug Report] Container upgraded from 0.20.0 to 0.20.1 fails to start

### ISSUE THREAD

**Issue by CaligulaCa3sar** [hkalexling/Mango#169] opened 2021-02-28 13:56 UTC
**Describe the bug**
Upgrading from 0.20.0 to 0.20.1 in Docker causes the container to fail to launch with the error:

"OCI runtime create failed: container_linux.go:345: starting container process caused \"exec: \\\"./mango\\\": stat ./mango: no such file or directory\": unknown"

Seems to be a result of the [relocation of the binary in this release](https://github.com/hkalexling/Mango/releases/tag/v0.20.1).

**To Reproduce**
1. Download latest release from the Docker repository.
2. Stop 0.20.0 container.
3. Clear the container.
4. Start the container.

**Expected behavior**
Image should work with the latest image release after clearing as this has worked with every previous release.

**Environment (please complete the following information):**
 - OS: Synology DSM 6.2.3
 - Docker version: 18.09.0
 - Mango Version: 0.20.1

**Comment by hkalexling** [comment] 2021-02-28 14:03
Hi, thanks for the bug report. 

What exactly did you do to upgrade the container? Could you please copy the commands you ran? I've tried the v0.20.1 docker image as a fresh container and it works without any issues. The containers are stateless so I am not sure why the upgrade would fail.

**Comment by CaligulaCa3sar** [comment] 2021-02-28 14:11
It's done through the DSM web GUI.  In the Docker dialogue, the process for upgrading the container is to download the latest image, stop the running container, right-click and choose "Clear" which clears the container settings and then start it again which recreates the container using the latest image.  This has always worked with prior upgrades where the binary location has not moved.

I should probably just recreate the container from scratch, but it would be nice to get to the bottom of the issue.  I will investigate more at my end.

**Comment by hkalexling** [comment] 2021-02-28 14:21
I see. Unfortunately, I don't use Synology and I am not familiar with the terminology they use, so I can't help with that. 

> I should probably just recreate the container from scratch


Yes, that's probably the best way to upgrade a container. Here's what I've done to upgrade a container from v0.20.0 to v0.20.1 using the docker CLI.

<details>
<summary>log</summary>

```
docker run --name test -it hkalexling/mango:v0.20.0
Unable to find image 'hkalexling/mango:v0.20.0' locally
v0.20.0: Pulling from hkalexling/mango
Digest: sha256:daf877ab9065fd42d00904724fce09bdb3584f6188a2e048f34254b28d7095f3
Status: Downloaded newer image for hkalexling/mango:v0.20.0


              _|      _|
              _|_|  _|_|    _|_|_|  _|_|_|      _|_|_|    _|_|
              _|  _|  _|  _|    _|  _|    _|  _|    _|  _|    _|
              _|      _|  _|    _|  _|    _|  _|    _|  _|    _|
              _|      _|    _|_|_|  _|    _|    _|_|_|    _|_|
                                                    _|
                                                _|_|


Mango - Manga Server and Web Reader. Version 0.20.0

The config file /root/.config/mango/config.yml does not exist. Dumping the default config there.
The config file has been created at /root/.config/mango/config.yml.
[INFO]    2021/02/28 14:11:24 | The DB directory /root/mango does not exist. Attepmting to create it
[INFO]    2021/02/28 14:11:24 | Migrating to CreateUsers (1)
[INFO]    2021/02/28 14:11:24 | Migrating to CreateIds (2)
[INFO]    2021/02/28 14:11:24 | Migrating to CreateThumbnails (3)
[INFO]    2021/02/28 14:11:24 | Migrating to CreateTags (4)
[INFO]    2021/02/28 14:11:24 | Migrating to CreateTitles (5)
[INFO]    2021/02/28 14:11:24 | Migrating to ForeignKeys (6)
[INFO]    2021/02/28 14:11:24 | Migrating to IDSignature (7)
[INFO]    2021/02/28 14:11:24 | Migrating to RelativePath (8)
[INFO]    2021/02/28 14:11:24 | Migrating to UnavailableIDs (9)
[INFO]    2021/02/28 14:11:24 | Migrating to RelativePathFix (10)
[INFO]    2021/02/28 14:11:24 | Job done
[NONE]    2021/02/28 14:11:25 | Initial user created. You can log in with {"username" => "admin", "password" => "e86e19459b9b4c6f97edbac95a2e38a2"}
[INFO]    2021/02/28 14:11:25 | The library directory /root/mango/library does not exist. Attempting to create it
[INFO]    2021/02/28 14:11:25 | Scanned 0 titles in 9.676852ms
^C%

λ alex_ling [~] → docker rm test
test

λ alex_ling [~] → docker run --name test -it hkalexling/mango:v0.20.1
Unable to find image 'hkalexling/mango:v0.20.1' locally
v0.20.1: Pulling from hkalexling/mango
Digest: sha256:9682c11418590fb288ab471b58ccbaee5258cdda10aa349e1d64d7edb3b335cd
Status: Downloaded newer image for hkalexling/mango:v0.20.1


              _|      _|
              _|_|  _|_|    _|_|_|  _|_|_|      _|_|_|    _|_|
              _|  _|  _|  _|    _|  _|    _|  _|    _|  _|    _|
              _|      _|  _|    _|  _|    _|  _|    _|  _|    _|
              _|      _|    _|_|_|  _|    _|    _|_|_|    _|_|
                                                    _|
                                                _|_|


Mango - Manga Server and Web Reader. Version 0.20.1

The config file /root/.config/mango/config.yml does not exist. Dumping the default config there.
The config file has been created at /root/.config/mango/config.yml.
[INFO]    2021/02/28 14:11:51 | The DB directory /root/mango does not exist. Attepmting to create it
[INFO]    2021/02/28 14:11:51 | Migrating to CreateUsers (1)
[INFO]    2021/02/28 14:11:51 | Migrating to CreateIds (2)
[INFO]    2021/02/28 14:11:51 | Migrating to CreateThumbnails (3)
[INFO]    2021/02/28 14:11:51 | Migrating to CreateTags (4)
[INFO]    2021/02/28 14:11:51 | Migrating to CreateTitles (5)
[INFO]    2021/02/28 14:11:51 | Migrating to ForeignKeys (6)
[INFO]    2021/02/28 14:11:51 | Migrating to IDSignature (7)
[INFO]    2021/02/28 14:11:51 | Migrating to RelativePath (8)
[INFO]    2021/02/28 14:11:51 | Migrating to UnavailableIDs (9)
[INFO]    2021/02/28 14:11:51 | Migrating to RelativePathFix (10)
[INFO]    2021/02/28 14:11:51 | Job done
[NONE]    2021/02/28 14:11:52 | Initial user created. You can log in with {"username" => "admin", "password" => "8dc1ab9449684b0da9ec329904cb1e4a"}
[INFO]    2021/02/28 14:11:52 | The library directory /root/mango/library does not exist. Attempting to create it
[INFO]    2021/02/28 14:11:52 | Scanned 0 titles in 5.936412ms
```

</details>


Since it's not an issue with Mango itself, I am closing this for now. It would be great if you could update us if you find the root cause as it might help others :)

**Closed by hkalexling** 2021-02-28 14:21 UTC
Labels: bug
