### ISSUE TITLE
[Bug Report] Unable to get file info: '/root/mango': Value too large for defined data type

### ISSUE THREAD

**Issue by SPJames** [hkalexling/Mango#100] opened 2020-08-30 17:37 UTC
**Describe the bug**
I encountered a bug while starting the docker container based on the new v0.11.1 arm32v7 build using a Raspberry pi 4.
I followed the build steps as defined in this [Wiki page](https://github.com/hkalexling/Mango/wiki/Platform-Support)
The program was unable to start.
The actual error was: 
_Unhandled exception: Unable to get file info: '/root/mango': Value too large for defined data type (File::Error)_

**To Reproduce**
1. Clone the repo
2. Add the mango-arm32v7.o
3. Configure the .env and docker-compose.yml
4. docker-compose up

**Expected behavior**
The program to be running and accessible via the configured port.

**Environment (please complete the following information):**
 - OS: Raspbian 10 (buster)
 - Mango Version  v0.11.0

**Docker (if you are running Mango in a Docker container)**
docker-compose.yml: 
`version: '3'
services:
  mango:
    container_name: mango
    build:
      context: .
     dockerfile: ./Dockerfile.arm32v7
    expose:
      - ${PORT}
    ports:
     - "${PORT}:9000"
    volumes:
      - ${MAIN_DIRECTORY_PATH}:/root/mango
      - ${CONFIG_DIRECTORY_PATH}:/root/.config/mango`
.env:
`PORT=9010
MAIN_DIRECTORY_PATH=/storage/Manga
CONFIG_DIRECTORY_PATH=/NAS/Prpgrams/ProgramData/Mango`

**Additional context**
This was the full stacktrace:
>  from usr/share/crystal/src/crystal/system/unix/file.cr:44:9 in 'info?'
  from usr/share/crystal/src/file.cr:132:5 in 'default'
  from __w/Mango/Mango/src/queue.cr:11:7 in 'default'
  from __w/Mango/Mango/src/mango.cr:47:3 in '->'
  from usr/share/crystal/src/hash.cr:896:11 in '__crystal_main'
  from usr/share/crystal/src/crystal/main.cr:39:9 in 'main'
  from __libc_start_main

**Comment by hkalexling** [comment] 2020-08-31 08:25
Hi, thanks for the report! I guess it's related to https://github.com/crystal-lang/crystal/issues/9297 so it's a compiler issue. I will see what I can do.

I use Ubuntu on my RPi 3 and the container works fine. Could you please do the following to help diagnose the issue?

1. Check the size of your main directory (`/storage/Manga`). If it's larger than 2GB, please map `MAIN_DIRECTORY_PATH` to a smaller directory and see if it works.
2. Shell into the container and run `stat` on `/root/mango`. You can run `docker run -it <image_id> /bin/bash` to get into the container and then run `stat /root/mango` there.

**Comment by SPJames** [comment] 2020-08-31 16:12
Thanks for the quick reply.

I don't know if its related to the crystal-lang issue. As for the 2 questions:
1. The `/storage/Manga` folder is currently empty, I was planning on building my library after I have the application running.
2. I shelled into the container and found that `/root` was completely empty (outside of the standard `.bashrc`/`.profile`). So my best guess would be that somewhere during the build of the docker image or startup of the container something went wrong.
Would it be useful to share the docker build output?
Or would mapping the config and main dir to a different folder work (I shall try this and see if it works)?

Again thanks for the quick help!

**Comment by SPJames** [comment] 2020-08-31 16:30
A

> Thanks for the quick reply.
> 
> I don't know if its related to the crystal-lang issue. As for the 2 questions:
> 
> 1. The `/storage/Manga` folder is currently empty, I was planning on building my library after I have the application running.
> 2. I shelled into the container and found that `/root` was completely empty (outside of the standard `.bashrc`/`.profile`). So my best guess would be that somewhere during the build of the docker image or startup of the container something went wrong.
>    Would it be useful to share the docker build output?
>    Or would mapping the config and main dir to a different folder work (I shall try this and see if it works)?
> 
> Again thanks for the quick help!

After rebuilding the image but instead pointing the docker-compose.yml location to `/app/` it worked :)
Maybe it was a onetime error.

**Comment by hkalexling** [comment] 2020-09-01 16:58
Glad that it's working now! As I can't reproduce the error I will be closing this for now. Please feel free to comment if you or anyone else got the same error, and I will reopen the issue.

**Closed by hkalexling** 2020-09-01 16:58 UTC
Labels: bug
